spring:
  application:
    name: Enotes_API_Service
  profiles:
    active: dev

# =========================
# DEV PROFILE
# =========================
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/enotes_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: smtp.gmail.com
    username: techlife246@gmail.com
    password: nflw mgjz qlld huay
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

file:
  upload:
    path: notes/

# =========================
# TEST PROFILE
# =========================
---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:mysql://localhost:3306/enotes_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none

# =========================
# UAT PROFILE
# =========================
---
spring:
  config:
    activate:
      on-profile: uat

  datasource:
    url: jdbc:mysql://localhost:3306/enotes_uat
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

# =========================
# PROD PROFILE
# =========================
---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://localhost:3306/enotes_prod
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234